# copy this from my other project(https://github.com/coder-salman/tfcodeforAzure)

---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  comments-indentation: disable
  document-start: disable

ignore: |
  node_modules/
  .github/

